# gradle.properties — root projektu LegendaryOS App
# WYMAGANE dla modułu android — AndroidX
android.useAndroidX=true

# Kotlin / Compose
kotlin.code.style=official

# Wydajność
org.gradle.jvmargs=-Xmx4g -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Android
android.nonTransitiveRClass=true
